import pickle
from sklearn.feature_extraction.text import TfidfVectorizer #type: ignore
from sklearn.naive_bayes import MultinomialNB #type: ignore
from sklearn.pipeline import make_pipeline #type: ignore


#-----------------------------Entrenar IA con datos------------------------------#
def entrenar_modelo():
    datos = [
        ("El monitor no enciende y la luz de encendido parpadea constantemente.", "HARDWARE", "Grave"),
        ("El teclado tiene varias teclas que no funcionan correctamente.", "HARDWARE", "Media"),
        ("El ordenador se apaga de forma repentina después de unos minutos de uso.", "HARDWARE", "Muy Grave"),
        ("El ratón no responde ni se mueve en pantalla.", "HARDWARE", "Baja"),
        ("El disco duro emite ruidos extraños y el sistema tarda en iniciar.", "HARDWARE", "Alta"),
        ("El ventilador del CPU no gira y el equipo se sobrecalienta.", "HARDWARE", "Grave"),
        ("El puerto USB no detecta ningún dispositivo conectado.", "HARDWARE", "Media"),
        ("El cable de red está dañado y no hay conexión a Internet.", "HARDWARE", "Alta"),
        ("El ordenador portátil no carga la batería al estar conectado.", "HARDWARE", "Grave"),
        ("El proyector muestra una imagen borrosa incluso después de enfocar.", "HARDWARE", "Baja"),
        ("El sistema operativo no inicia y muestra un error crítico de arranque.", "SOFTWARE", "Muy Grave"),
        ("El programa de gestión se congela al intentar guardar los cambios.", "SOFTWARE", "Alta"),
        ("El antivirus no se actualiza y muestra errores de conexión.", "SOFTWARE", "Media"),
        ("El navegador abre ventanas emergentes constantemente.", "SOFTWARE", "Baja"),
        ("El usuario no puede iniciar sesión en el sistema por error de credenciales.", "SOFTWARE", "Media"),
        ("El sistema muestra una pantalla azul al instalar una actualización.", "SOFTWARE", "Grave"),
        ("La base de datos se corrompió y no permite acceder a la información.", "SOFTWARE", "Muy Grave"),
        ("El correo electrónico no envía ni recibe mensajes correctamente.", "SOFTWARE", "Alta"),
        ("La aplicación de contabilidad muestra datos duplicados en los reportes.", "SOFTWARE", "Baja"),
        ("El sistema se reinicia automáticamente sin previo aviso.", "SOFTWARE", "Grave"),
        ("La impresora no responde y muestra un error de atasco aunque no hay papel bloqueado.", "HARDWARE", "Media"),
        ("El disco externo no es reconocido por el equipo en ningún puerto.", "HARDWARE", "Alta"),
        ("La pantalla del portátil parpadea constantemente y cambia de brillo sola.", "HARDWARE", "Grave"),
        ("El cable HDMI no transmite señal al monitor secundario.", "HARDWARE", "Baja"),
        ("El ventilador de la fuente de alimentación hace un ruido muy fuerte.", "HARDWARE", "Alta"),
        ("El teclado inalámbrico no se conecta pese a cambiar las pilas.", "HARDWARE", "Media"),
        ("El equipo emite pitidos al arrancar y no muestra imagen.", "HARDWARE", "Muy Grave"),
        ("La cámara web integrada no funciona tras actualizar el sistema.", "HARDWARE", "Media"),
        ("El lector de tarjetas SD no detecta ninguna memoria insertada.", "HARDWARE", "Baja"),
        ("El sistema no reconoce la memoria RAM recién instalada.", "HARDWARE", "Grave"),
        ("El sistema de inventario se cierra solo al intentar generar un informe.", "SOFTWARE", "Alta"),
        ("El programa de correo se queda cargando indefinidamente al abrir adjuntos.", "SOFTWARE", "Media"),
        ("El navegador no guarda las contraseñas a pesar de tener la opción activada.", "SOFTWARE", "Baja"),
        ("El software de diseño se bloquea al importar archivos grandes.", "SOFTWARE", "Alta"),
        ("El sistema operativo tarda más de 10 minutos en iniciar sesión.", "SOFTWARE", "Grave"),
        ("El antivirus detecta un archivo del sistema como amenaza y lo elimina.", "SOFTWARE", "Muy Grave"),
        ("La aplicación de mensajería no muestra notificaciones entrantes.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no realiza los respaldos programados.", "SOFTWARE", "Grave"),
        ("El programa contable muestra errores al calcular los totales.", "SOFTWARE", "Baja"),
        ("El sistema muestra errores de permisos al intentar abrir carpetas compartidas.", "SOFTWARE", "Alta"),
        ("El ratón deja de funcionar de forma intermitente y el cursor se congela.", "HARDWARE", "Media"),
        ("El disco duro hace ruidos extraños y el sistema no inicia correctamente.", "HARDWARE", "Muy Grave"),
        ("El monitor presenta líneas horizontales y una imagen distorsionada.", "HARDWARE", "Alta"),
        ("El puerto USB delantero no detecta ningún dispositivo conectado.", "HARDWARE", "Baja"),
        ("La batería del portátil se descarga completamente en menos de 10 minutos.", "HARDWARE", "Alta"),
        ("El botón de encendido no responde al intentar iniciar el equipo.", "HARDWARE", "Grave"),
        ("Los auriculares conectados al equipo no emiten sonido.", "HARDWARE", "Media"),
        ("La impresora imprime con manchas negras en todas las hojas.", "HARDWARE", "Baja"),
        ("El ventilador del procesador no gira y el equipo se sobrecalienta.", "HARDWARE", "Muy Grave"),
        ("El escáner no realiza la digitalización y muestra error de conexión.", "HARDWARE", "Media"),
        ("El sistema no permite iniciar sesión y muestra un error de autenticación.", "SOFTWARE", "Alta"),
        ("El navegador se cierra repentinamente al abrir una nueva pestaña.", "SOFTWARE", "Media"),
        ("El programa de facturación genera reportes con datos incompletos.", "SOFTWARE", "Alta"),
        ("El antivirus no actualiza su base de datos desde hace varios días.", "SOFTWARE", "Grave"),
        ("El sistema operativo muestra una pantalla azul al intentar reiniciar.", "SOFTWARE", "Muy Grave"),
        ("El reproductor de video no reconoce los formatos más comunes.", "SOFTWARE", "Baja"),
        ("La aplicación de correo no sincroniza los mensajes enviados.", "SOFTWARE", "Media"),
        ("El software de diseño no guarda los cambios y muestra error al guardar.", "SOFTWARE", "Alta"),
        ("El sistema de control de acceso no registra las entradas del día.", "SOFTWARE", "Grave"),
        ("El programa de ofimática tarda varios minutos en abrir cualquier documento.", "SOFTWARE", "Baja"),
        ("El ventilador de la tarjeta gráfica no funciona y el equipo se apaga por sobrecalentamiento.", "HARDWARE", "Muy Grave"),
        ("El proyector no enciende y muestra luces intermitentes de error.", "HARDWARE", "Alta"),
        ("La impresora muestra un mensaje de cartucho no reconocido.", "HARDWARE", "Media"),
        ("El disco SSD no es detectado por el BIOS del ordenador.", "HARDWARE", "Grave"),
        ("El teclado presenta doble pulsación en varias teclas.", "HARDWARE", "Media"),
        ("El ratón inalámbrico pierde señal constantemente.", "HARDWARE", "Baja"),
        ("El monitor táctil no responde a los toques en varias zonas.", "HARDWARE", "Alta"),
        ("El micrófono incorporado no capta sonido alguno.", "HARDWARE", "Baja"),
        ("La placa base emite pitidos al iniciar y no arranca el sistema.", "HARDWARE", "Muy Grave"),
        ("La memoria RAM instalada provoca reinicios inesperados del sistema.", "HARDWARE", "Grave"),
        ("El software de contabilidad muestra errores al calcular impuestos.", "SOFTWARE", "Alta"),
        ("El antivirus elimina archivos del sistema sin previo aviso.", "SOFTWARE", "Muy Grave"),
        ("El navegador no carga páginas web correctamente y se queda en blanco.", "SOFTWARE", "Media"),
        ("El gestor de correos no envía mensajes a determinadas cuentas.", "SOFTWARE", "Media"),
        ("La aplicación de mensajería falla al enviar fotos o videos.", "SOFTWARE", "Baja"),
        ("El sistema operativo se congela al intentar abrir varias ventanas.", "SOFTWARE", "Grave"),
        ("El programa de diseño gráfico no abre archivos pesados y se bloquea.", "SOFTWARE", "Alta"),
        ("El software de bases de datos arroja errores de conexión intermitentes.", "SOFTWARE", "Grave"),
        ("El sistema de backups no realiza copias de seguridad automáticas.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce ciertos formatos de video.", "SOFTWARE", "Baja"),
        ("El portátil no detecta el adaptador de corriente y no carga la batería.", "HARDWARE", "Grave"),
        ("El teclado mecánico hace doble pulsación en varias teclas aleatoriamente.", "HARDWARE", "Media"),
        ("La pantalla externa no muestra señal a pesar de estar conectada correctamente.", "HARDWARE", "Alta"),
        ("El ventilador del portátil gira de forma errática y produce ruido constante.", "HARDWARE", "Media"),
        ("El disco duro externo deja de funcionar tras unos minutos de uso.", "HARDWARE", "Muy Grave"),
        ("El ratón USB no responde al moverlo o hacer clic.", "HARDWARE", "Baja"),
        ("La impresora imprime con rayas horizontales en todas las páginas.", "HARDWARE", "Alta"),
        ("El altavoz integrado no emite sonido en ninguna aplicación.", "HARDWARE", "Media"),
        ("La cámara web muestra imagen distorsionada y parpadea constantemente.", "HARDWARE", "Grave"),
        ("El puerto HDMI del equipo no transmite audio ni video correctamente.", "HARDWARE", "Alta"),
        ("El software de gestión de inventarios no guarda los cambios realizados.", "SOFTWARE", "Alta"),
        ("El navegador bloquea varias páginas sin motivo aparente.", "SOFTWARE", "Baja"),
        ("El sistema operativo tarda demasiado en arrancar y muestra errores de carga.", "SOFTWARE", "Grave"),
        ("El antivirus detecta falsos positivos y elimina archivos necesarios.", "SOFTWARE", "Muy Grave"),
        ("El programa de mensajería no envía ni recibe mensajes correctamente.", "SOFTWARE", "Media"),
        ("El software de contabilidad no calcula correctamente los totales de ventas.", "SOFTWARE", "Alta"),
        ("El sistema de correo electrónico se queda colgado al abrir adjuntos grandes.", "SOFTWARE", "Media"),
        ("La aplicación de diseño gráfico se bloquea al importar imágenes pesadas.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce ciertos formatos de audio.", "SOFTWARE", "Baja"),
        ("El sistema de backups no realiza copias automáticas según la programación.", "SOFTWARE", "Grave"),
        ("El portátil no reconoce la tarjeta de red y no puede conectarse a Internet.", "HARDWARE", "Alta"),
        ("El ventilador del CPU hace un ruido excesivo y provoca sobrecalentamiento.", "HARDWARE", "Grave"),
        ("El disco duro interno muestra errores de lectura y archivos dañados.", "HARDWARE", "Muy Grave"),
        ("El monitor táctil no responde a ningún toque, aunque está calibrado.", "HARDWARE", "Grave"),
        ("El teclado no enciende la retroiluminación y algunas teclas no funcionan.", "HARDWARE", "Media"),
        ("El ratón óptico tiene retraso constante y el cursor salta de posición.", "HARDWARE", "Media"),
        ("El proyector se apaga solo después de unos minutos de uso.", "HARDWARE", "Alta"),
        ("El puerto USB-C no transmite datos ni carga dispositivos.", "HARDWARE", "Alta"),
        ("La batería del portátil se hincha y el equipo no arranca.", "HARDWARE", "Muy Grave"),
        ("La impresora deja marcas de tinta en todas las hojas impresas.", "HARDWARE", "Baja"),
        ("El sistema de gestión de clientes pierde datos al cerrar la aplicación.", "SOFTWARE", "Muy Grave"),
        ("El navegador no reproduce videos de ciertas plataformas web.", "SOFTWARE", "Media"),
        ("El programa de correo bloquea mensajes entrantes sin motivo.", "SOFTWARE", "Alta"),
        ("El antivirus no detecta malware conocido y genera falsos negativos.", "SOFTWARE", "Grave"),
        ("El sistema operativo genera errores al instalar actualizaciones.", "SOFTWARE", "Alta"),
        ("El software de contabilidad duplica registros y genera inconsistencias.", "SOFTWARE", "Grave"),
        ("El programa de mensajería envía notificaciones erróneas constantemente.", "SOFTWARE", "Baja"),
        ("El sistema de bases de datos no permite consultas simultáneas.", "SOFTWARE", "Alta"),
        ("La aplicación de edición de video se cierra inesperadamente al exportar archivos grandes.", "SOFTWARE", "Muy Grave"),
        ("El reproductor de audio pierde la sincronización con los subtítulos.", "SOFTWARE", "Baja"),
        ("El equipo portátil se calienta demasiado aunque la ventilación está limpia.", "HARDWARE", "Grave"),
        ("El monitor no ajusta correctamente el brillo automático y parpadea.", "HARDWARE", "Media"),
        ("El disco SSD externo deja de funcionar de manera intermitente.", "HARDWARE", "Alta"),
        ("El teclado inalámbrico pierde conexión varias veces durante el uso.", "HARDWARE", "Media"),
        ("El ratón no responde cuando se conecta a ciertos puertos USB.", "HARDWARE", "Baja"),
        ("El proyector proyecta colores distorsionados y la imagen se ve borrosa.", "HARDWARE", "Alta"),
        ("El ventilador del CPU hace ruidos extraños y la PC se apaga sola.", "HARDWARE", "Muy Grave"),
        ("La impresora muestra mensajes de error de alimentación de papel inexistente.", "HARDWARE", "Media"),
        ("El puerto HDMI no transmite señal de audio, solo video.", "HARDWARE", "Baja"),
        ("La memoria RAM instalada provoca bloqueos aleatorios del sistema.", "HARDWARE", "Grave"),
        ("El sistema operativo se reinicia solo al abrir ciertas aplicaciones.", "SOFTWARE", "Grave"),
        ("El navegador no guarda favoritos ni historial correctamente.", "SOFTWARE", "Baja"),
        ("El programa de contabilidad no aplica correctamente los descuentos.", "SOFTWARE", "Alta"),
        ("El antivirus no elimina amenazas detectadas en tiempo real.", "SOFTWARE", "Muy Grave"),
        ("El software de edición de imágenes se cierra inesperadamente al exportar.", "SOFTWARE", "Alta"),
        ("El gestor de correos envía duplicados algunos mensajes sin razón aparente.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no completa los respaldos programados.", "SOFTWARE", "Grave"),
        ("El reproductor multimedia no reproduce algunos formatos de audio.", "SOFTWARE", "Baja"),
        ("La aplicación de mensajería muestra notificaciones incorrectas o retrasadas.", "SOFTWARE", "Media"),
        ("El sistema operativo no reconoce ciertos controladores tras la actualización.", "SOFTWARE", "Alta"),
        ("El teclado presenta teclas atascadas que no registran pulsación.", "HARDWARE", "Media"),
        ("El ratón inalámbrico tiene retraso constante y desconexiones frecuentes.", "HARDWARE", "Alta"),
        ("El monitor muestra sombras y colores desalineados en la pantalla.", "HARDWARE", "Grave"),
        ("La batería del portátil se descarga muy rápido pese a estar cargada.", "HARDWARE", "Alta"),
        ("El disco duro hace clics al intentar acceder a los archivos.", "HARDWARE", "Muy Grave"),
        ("El ventilador del portátil gira a máxima velocidad sin motivo.", "HARDWARE", "Media"),
        ("La impresora no reconoce cartuchos originales y no imprime.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar tras conectar varios dispositivos.", "HARDWARE", "Baja"),
        ("El equipo emite pitidos al iniciar y no carga el sistema operativo.", "HARDWARE", "Muy Grave"),
        ("El lector de CD/DVD no lee discos aunque estén en buen estado.", "HARDWARE", "Grave"),
        ("El sistema de facturación muestra errores al calcular impuestos.", "SOFTWARE", "Alta"),
        ("El programa de mensajería no sincroniza los mensajes entre dispositivos.", "SOFTWARE", "Media"),
        ("El antivirus genera falsos positivos y bloquea programas esenciales.", "SOFTWARE", "Muy Grave"),
        ("El navegador no permite descargar archivos desde ciertas páginas.", "SOFTWARE", "Media"),
        ("El sistema operativo se congela al abrir varias aplicaciones simultáneamente.", "SOFTWARE", "Grave"),
        ("El software de diseño gráfico no guarda los cambios correctamente.", "SOFTWARE", "Alta"),
        ("El reproductor de video no reproduce ciertos formatos de archivo.", "SOFTWARE", "Baja"),
        ("La aplicación de correo no envía mensajes a determinados destinatarios.", "SOFTWARE", "Alta"),
        ("El sistema de copias de seguridad falla al intentar crear respaldos programados.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad duplica registros al generar reportes.", "SOFTWARE", "Media"),
        ("El portátil no reconoce la tarjeta de red interna y no se conecta a Internet.", "HARDWARE", "Alta"),
        ("El ventilador del CPU hace un ruido constante y provoca apagados inesperados.", "HARDWARE", "Grave"),
        ("El disco duro externo deja de funcionar tras unos minutos de uso intenso.", "HARDWARE", "Muy Grave"),
        ("El monitor muestra parpadeos y cambios de color aleatorios.", "HARDWARE", "Media"),
        ("El teclado inalámbrico no responde a ciertas teclas y se reinicia solo.", "HARDWARE", "Alta"),
        ("El ratón pierde precisión y el cursor salta en la pantalla.", "HARDWARE", "Media"),
        ("La impresora imprime con tinta corrugada y líneas irregulares.", "HARDWARE", "Baja"),
        ("El puerto USB-C no transmite datos aunque carga dispositivos correctamente.", "HARDWARE", "Alta"),
        ("La batería del portátil no carga y el equipo no enciende.", "HARDWARE", "Muy Grave"),
        ("El proyector emite luz pero no proyecta la imagen correctamente.", "HARDWARE", "Grave"),
        ("El sistema operativo no inicia y muestra pantalla negra al encender.", "SOFTWARE", "Muy Grave"),
        ("El navegador no permite abrir nuevas pestañas y se cierra inesperadamente.", "SOFTWARE", "Alta"),
        ("El programa de mensajería envía mensajes duplicados a todos los contactos.", "SOFTWARE", "Media"),
        ("El antivirus no detecta amenazas recientes y deja el sistema vulnerable.", "SOFTWARE", "Muy Grave"),
        ("El software de contabilidad genera totales incorrectos en facturas.", "SOFTWARE", "Alta"),
        ("El reproductor de video no carga subtítulos correctamente.", "SOFTWARE", "Baja"),
        ("El gestor de correo bloquea ciertos adjuntos y no los envía.", "SOFTWARE", "Media"),
        ("El sistema de backups no completa las copias según lo programado.", "SOFTWARE", "Grave"),
        ("La aplicación de diseño gráfico se cierra al importar imágenes grandes.", "SOFTWARE", "Alta"),
        ("El sistema operativo muestra errores de actualización y no reinicia.", "SOFTWARE", "Grave"),
        ("El teclado mecánico no registra algunas combinaciones de teclas.", "HARDWARE", "Media"),
        ("El ratón USB se desconecta continuamente al moverlo por el escritorio.", "HARDWARE", "Baja"),
        ("El monitor se apaga de forma inesperada mientras se trabaja.", "HARDWARE", "Alta"),
        ("La batería del portátil se hincha y obliga a apagar el equipo.", "HARDWARE", "Muy Grave"),
        ("El disco duro interno genera ruidos extraños y errores de lectura.", "HARDWARE", "Grave"),
        ("El ventilador del CPU no funciona y el equipo se sobrecalienta.", "HARDWARE", "Muy Grave"),
        ("La impresora imprime páginas en blanco aunque el cartucho esté lleno.", "HARDWARE", "Alta"),
        ("El puerto HDMI no transmite señal a monitores externos.", "HARDWARE", "Grave"),
        ("El portátil no detecta la memoria RAM instalada correctamente.", "HARDWARE", "Alta"),
        ("El proyector proyecta la imagen distorsionada y con líneas horizontales.", "HARDWARE", "Media"),
        ("El software de contabilidad no aplica correctamente los impuestos.", "SOFTWARE", "Alta"),
        ("El navegador no permite iniciar sesión en ciertas páginas web.", "SOFTWARE", "Media"),
        ("El antivirus elimina archivos importantes sin preguntar.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no envía mensajes con archivos adjuntos pesados.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce algunos archivos de audio.", "SOFTWARE", "Baja"),
        ("El sistema de backups no realiza las copias según el horario programado.", "SOFTWARE", "Grave"),
        ("La aplicación de diseño gráfico se cierra al intentar exportar proyectos grandes.", "SOFTWARE", "Muy Grave"),
        ("El programa de mensajería no sincroniza los contactos entre dispositivos.", "SOFTWARE", "Media"),
        ("El sistema operativo se congela al abrir múltiples aplicaciones.", "SOFTWARE", "Grave"),
        ("El software de edición de video no renderiza correctamente los archivos de gran tamaño.", "SOFTWARE", "Alta"),
        ("El teclado inalámbrico no responde después de varios minutos de inactividad.", "HARDWARE", "Media"),
        ("El ratón óptico deja de funcionar al moverlo sobre ciertas superficies.", "HARDWARE", "Baja"),
        ("El monitor parpadea intermitentemente y muestra líneas horizontales.", "HARDWARE", "Alta"),
        ("La batería del portátil no se carga aunque el cargador funcione correctamente.", "HARDWARE", "Grave"),
        ("El disco duro externo no es reconocido por el sistema operativo.", "HARDWARE", "Muy Grave"),
        ("El ventilador de la torre gira muy rápido y genera ruido excesivo.", "HARDWARE", "Media"),
        ("La impresora no detecta papel aunque la bandeja esté llena.", "HARDWARE", "Alta"),
        ("El puerto USB no transmite datos y provoca desconexiones frecuentes.", "HARDWARE", "Baja"),
        ("El equipo emite pitidos al iniciar y no arranca el sistema operativo.", "HARDWARE", "Muy Grave"),
        ("El proyector no ajusta correctamente la resolución de la imagen.", "HARDWARE", "Grave"),
        ("El sistema de facturación muestra errores al generar reportes.", "SOFTWARE", "Alta"),
        ("El navegador se congela al abrir varias pestañas simultáneamente.", "SOFTWARE", "Media"),
        ("El antivirus no actualiza sus definiciones y deja el equipo vulnerable.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo bloquea mensajes entrantes de determinados remitentes.", "SOFTWARE", "Alta"),
        ("El reproductor de audio no reproduce algunos formatos de archivo.", "SOFTWARE", "Baja"),
        ("El software de diseño gráfico no guarda correctamente los cambios realizados.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no muestra notificaciones de mensajes nuevos.", "SOFTWARE", "Media"),
        ("El sistema operativo muestra errores al instalar actualizaciones.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera cálculos incorrectos en informes.", "SOFTWARE", "Alta"),
        ("El reproductor de video se cierra inesperadamente al reproducir archivos pesados.", "SOFTWARE", "Muy Grave"),
        ("El teclado mecánico no registra ciertas combinaciones de teclas simultáneamente.", "HARDWARE", "Media"),
        ("El ratón inalámbrico pierde señal al alejarlo de la computadora.", "HARDWARE", "Baja"),
        ("El monitor tiene zonas oscuras que dificultan ver el contenido correctamente.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga rápidamente aun estando completamente cargada.", "HARDWARE", "Grave"),
        ("El disco SSD interno genera errores de lectura aleatorios.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU no se activa y provoca sobrecalentamiento.", "HARDWARE", "Muy Grave"),
        ("La impresora imprime tinta corrida y letras borrosas.", "HARDWARE", "Alta"),
        ("El puerto USB deja de reconocer dispositivos después de varias conexiones.", "HARDWARE", "Baja"),
        ("El portátil no detecta la memoria RAM instalada y no arranca.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra la imagen con distorsión de color y líneas verticales.", "HARDWARE", "Grave"),
        ("El sistema operativo se reinicia solo al abrir programas pesados.", "SOFTWARE", "Grave"),
        ("El navegador no carga ciertas páginas web correctamente.", "SOFTWARE", "Media"),
        ("El antivirus elimina archivos esenciales del sistema por error.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no envía mensajes con archivos adjuntos grandes.", "SOFTWARE", "Alta"),
        ("El reproductor de video no reproduce subtítulos en formato estándar.", "SOFTWARE", "Baja"),
        ("El software de diseño gráfico se cierra al guardar proyectos grandes.", "SOFTWARE", "Muy Grave"),
        ("La aplicación de mensajería no sincroniza mensajes en todos los dispositivos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no realiza respaldos completos.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad duplica entradas al generar informes.", "SOFTWARE", "Alta"),
        ("El reproductor de audio pierde sincronización con la pista de video.", "SOFTWARE", "Baja"),
        ("El teclado no registra algunas teclas al presionarlas rápidamente.", "HARDWARE", "Media"),
        ("El ratón USB deja de funcionar después de unos minutos de uso.", "HARDWARE", "Baja"),
        ("El monitor muestra líneas verticales al encender la computadora.", "HARDWARE", "Alta"),
        ("La batería del portátil se sobrecalienta y reduce su duración.", "HARDWARE", "Grave"),
        ("El disco duro externo no permite copiar archivos grandes.", "HARDWARE", "Alta"),
        ("El ventilador de la torre gira constantemente y hace ruido fuerte.", "HARDWARE", "Media"),
        ("La impresora imprime doble página en lugar de una sola.", "HARDWARE", "Baja"),
        ("El puerto HDMI no reconoce algunos televisores externos.", "HARDWARE", "Alta"),
        ("El portátil no reconoce la tarjeta de red interna.", "HARDWARE", "Muy Grave"),
        ("El proyector se apaga solo tras minutos de funcionamiento.", "HARDWARE", "Grave"),
        ("El sistema operativo se congela al abrir varias aplicaciones a la vez.", "SOFTWARE", "Grave"),
        ("El navegador no abre nuevas pestañas al hacer clic en los enlaces.", "SOFTWARE", "Media"),
        ("El antivirus no detecta virus recientes y deja el equipo vulnerable.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo bloquea mensajes legítimos como spam.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce archivos en ciertos formatos.", "SOFTWARE", "Baja"),
        ("El software de edición de imágenes cierra la aplicación al exportar.", "SOFTWARE", "Muy Grave"),
        ("La aplicación de mensajería no actualiza los chats en tiempo real.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no completa los respaldos automáticos.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores en los totales finales.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene aleatoriamente durante la reproducción.", "SOFTWARE", "Media"),
        ("El teclado inalámbrico no se conecta automáticamente al encender el equipo.", "HARDWARE", "Media"),
        ("El ratón óptico pierde precisión al moverlo rápidamente sobre la alfombra.", "HARDWARE", "Baja"),
        ("El monitor tiene zonas borrosas que dificultan ver texto y gráficos.", "HARDWARE", "Alta"),
        ("La batería del portátil no alcanza el tiempo de uso prometido por el fabricante.", "HARDWARE", "Grave"),
        ("El disco duro interno genera errores al copiar archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU se detiene intermitentemente y provoca sobrecalentamiento.", "HARDWARE", "Grave"),
        ("La impresora imprime caracteres incompletos o distorsionados.", "HARDWARE", "Alta"),
        ("El puerto USB-C no reconoce algunos dispositivos de almacenamiento.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta gráfica externa conectada.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta imagen desplazada fuera de la pantalla.", "HARDWARE", "Grave"),
        ("El sistema operativo muestra mensajes de error al iniciar sesión.", "SOFTWARE", "Alta"),
        ("El navegador no guarda contraseñas y cookies correctamente.", "SOFTWARE", "Media"),
        ("El antivirus bloquea aplicaciones esenciales sin previo aviso.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no recibe mensajes nuevos de algunos remitentes.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia se cierra al reproducir archivos de gran tamaño.", "SOFTWARE", "Baja"),
        ("El software de edición de video no exporta con la resolución seleccionada.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería duplica notificaciones de mensajes entrantes.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no respalda ciertas carpetas importantes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera registros duplicados en la base de datos.", "SOFTWARE", "Alta"),
        ("El reproductor de audio pierde sincronización con el video durante la reproducción.", "SOFTWARE", "Media"),
        ("El teclado tiene teclas que se presionan solas al escribir rápido.", "HARDWARE", "Grave"),
        ("El ratón inalámbrico se desconecta al acercarse a otros dispositivos.", "HARDWARE", "Media"),
        ("El monitor muestra parpadeos al cambiar la resolución de pantalla.", "HARDWARE", "Alta"),
        ("La batería del portátil no carga al 100% aunque el cargador funcione.", "HARDWARE", "Alta"),
        ("El disco duro externo genera errores al transferir archivos pesados.", "HARDWARE", "Muy Grave"),
        ("El ventilador del equipo hace ruido excesivo incluso sin carga.", "HARDWARE", "Media"),
        ("La impresora imprime páginas cortadas y desalineadas.", "HARDWARE", "Baja"),
        ("El puerto USB deja de funcionar después de varios usos consecutivos.", "HARDWARE", "Media"),
        ("El portátil no reconoce el disco SSD instalado.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra colores desvanecidos y poco definidos.", "HARDWARE", "Alta"),
        ("El sistema operativo no guarda configuraciones al reiniciar.", "SOFTWARE", "Media"),
        ("El navegador pierde historial y marcadores sin previo aviso.", "SOFTWARE", "Baja"),
        ("El antivirus detecta amenazas inexistentes y bloquea archivos seguros.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía mensajes duplicados a todos los destinatarios.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no carga subtítulos correctamente en ciertos videos.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes se cierra al aplicar filtros complejos.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no sincroniza conversaciones recientes.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al respaldar unidades externas.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera cálculos erróneos al exportar reportes.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene inesperadamente al avanzar rápido en la línea de tiempo.", "SOFTWARE", "Grave"),
        ("El teclado numérico deja de funcionar intermitentemente.", "HARDWARE", "Media"),
        ("El ratón no responde al hacer doble clic en ciertas aplicaciones.", "HARDWARE", "Baja"),
        ("El monitor muestra imagen borrosa al cambiar de fuente de entrada.", "HARDWARE", "Alta"),
        ("La batería del portátil se calienta demasiado al cargar.", "HARDWARE", "Grave"),
        ("El disco duro interno falla al arrancar el sistema operativo.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU produce vibraciones que afectan al equipo.", "HARDWARE", "Media"),
        ("La impresora imprime texto incompleto en documentos largos.", "HARDWARE", "Alta"),
        ("El puerto USB no reconoce discos externos grandes.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta de red Wi-Fi interna.", "HARDWARE", "Muy Grave"),
        ("El proyector pierde conexión con la computadora durante la presentación.", "HARDWARE", "Grave"),
        ("El sistema operativo no instala actualizaciones críticas.", "SOFTWARE", "Muy Grave"),
        ("El navegador no reproduce videos en sitios de streaming.", "SOFTWARE", "Alta"),
        ("El antivirus elimina archivos esenciales del sistema sin preguntar.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no sincroniza carpetas compartidas.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia se bloquea al abrir listas de reproducción largas.", "SOFTWARE", "Media"),
        ("El software de diseño gráfico genera archivos corruptos al exportar.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería envía mensajes duplicados a varios contactos.", "SOFTWARE", "Media"),
        ("El sistema de backups no guarda correctamente los cambios recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad no calcula correctamente los impuestos.", "SOFTWARE", "Alta"),
        ("El reproductor de video se queda sin audio al avanzar rápidamente en la línea de tiempo.", "SOFTWARE", "Media"),
        ("El teclado inalámbrico requiere reiniciar la conexión constantemente.", "HARDWARE", "Media"),
        ("El ratón pierde precisión al moverlo sobre superficies reflectantes.", "HARDWARE", "Baja"),
        ("El monitor muestra líneas de color al encender el equipo.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga completamente en poco tiempo.", "HARDWARE", "Grave"),
        ("El disco duro externo no permite formatear correctamente.", "HARDWARE", "Muy Grave"),
        ("El ventilador del equipo hace ruido irregular al cambiar la carga.", "HARDWARE", "Media"),
        ("La impresora imprime imágenes distorsionadas y borrosas.", "HARDWARE", "Alta"),
        ("El puerto USB no reconoce ciertos dispositivos antiguos.", "HARDWARE", "Baja"),
        ("El portátil no arranca debido a un fallo de la memoria RAM.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta imagen con colores desbalanceados.", "HARDWARE", "Grave"),
        ("El sistema operativo no carga la pantalla de inicio correctamente.", "SOFTWARE", "Grave"),
        ("El navegador cierra pestañas sin previo aviso al abrir varias simultáneamente.", "SOFTWARE", "Media"),
        ("El antivirus detecta amenazas falsas constantemente.", "SOFTWARE", "Alta"),
        ("El gestor de correo no muestra mensajes de ciertos contactos.", "SOFTWARE", "Media"),
        ("El reproductor multimedia no reconoce algunos códecs.", "SOFTWARE", "Baja"),
        ("El software de edición de imágenes no aplica filtros correctamente.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no actualiza los estados de los contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad omite archivos de carpetas específicas.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad no exporta reportes en formato correcto.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene y pierde frames durante la reproducción.", "SOFTWARE", "Media"),
        ("El teclado tiene teclas que se quedan presionadas después de soltarlas.", "HARDWARE", "Grave"),
        ("El ratón se desconecta al cambiar el puerto USB.", "HARDWARE", "Media"),
        ("El monitor muestra imagen borrosa al ajustar el brillo máximo.", "HARDWARE", "Alta"),
        ("La batería del portátil no alcanza más de 30 minutos de uso.", "HARDWARE", "Muy Grave"),
        ("El disco duro externo genera errores de lectura y escritura.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU no regula la velocidad correctamente y sobrecalienta.", "HARDWARE", "Grave"),
        ("La impresora imprime líneas en blanco entre palabras.", "HARDWARE", "Baja"),
        ("El puerto USB-C no transfiere datos a alta velocidad.", "HARDWARE", "Media"),
        ("El portátil no reconoce la tarjeta gráfica integrada.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra imagen desenfocada incluso ajustando el enfoque.", "HARDWARE", "Alta"),
        ("El sistema operativo se congela al abrir el panel de control.", "SOFTWARE", "Grave"),
        ("El navegador pierde sesión en algunos sitios web automáticamente.", "SOFTWARE", "Media"),
        ("El antivirus no detecta malware en archivos descargados recientes.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo bloquea correos importantes como spam.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce ciertos formatos de subtítulos.", "SOFTWARE", "Baja"),
        ("El software de diseño gráfico falla al exportar capas individuales.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería envía mensajes fuera de orden.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no respalda unidades externas correctamente.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera duplicados en el registro de transacciones.", "SOFTWARE", "Alta"),
        ("El reproductor de video se congela al avanzar rápidamente en la línea de tiempo.", "SOFTWARE", "Media"),
        ("El teclado no responde cuando se conecta después de dormir el equipo.", "HARDWARE", "Media"),
        ("El ratón tiene movimientos erráticos en la superficie del escritorio.", "HARDWARE", "Baja"),
        ("El monitor presenta parpadeos al conectar dispositivos HDMI externos.", "HARDWARE", "Alta"),
        ("La batería del portátil no carga al 50% aunque el cargador funcione.", "HARDWARE", "Grave"),
        ("El disco duro interno hace ruidos extraños y genera errores de acceso.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU gira constantemente aunque la computadora esté en reposo.", "HARDWARE", "Media"),
        ("La impresora imprime páginas con manchas de tinta aleatorias.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar tras conectar varios dispositivos seguidos.", "HARDWARE", "Baja"),
        ("El portátil no detecta la memoria RAM instalada correctamente.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta imágenes con bordes cortados.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite instalar actualizaciones de seguridad.", "SOFTWARE", "Muy Grave"),
        ("El navegador no reproduce videos en ciertas plataformas de streaming.", "SOFTWARE", "Alta"),
        ("El antivirus bloquea aplicaciones esenciales del sistema sin advertencia.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no muestra correctamente los correos con adjuntos pesados.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde el audio en videos largos.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no guarda los cambios realizados.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no sincroniza correctamente con la nube.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no respalda ciertas carpetas críticas.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores en cálculos de nómina.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene y retrasa el audio al avanzar rápidamente.", "SOFTWARE", "Media"),
        ("El teclado inalámbrico no se conecta después de reiniciar el equipo.", "HARDWARE", "Media"),
        ("El ratón presenta retraso al moverlo rápidamente en juegos.", "HARDWARE", "Alta"),
        ("El monitor parpadea al usar ciertas resoluciones personalizadas.", "HARDWARE", "Grave"),
        ("La batería del portátil se sobrecalienta mientras carga.", "HARDWARE", "Grave"),
        ("El disco duro externo no permite eliminar archivos correctamente.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace ruido irregular y constante.", "HARDWARE", "Media"),
        ("La impresora imprime documentos con líneas horizontales.", "HARDWARE", "Alta"),
        ("El puerto USB no reconoce dispositivos conectados intermitentemente.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta de red inalámbrica.", "HARDWARE", "Muy Grave"),
        ("El proyector pierde la conexión con el portátil después de minutos.", "HARDWARE", "Grave"),
        ("El sistema operativo se congela al abrir múltiples ventanas de explorador.", "SOFTWARE", "Grave"),
        ("El navegador no carga ciertas páginas web correctamente.", "SOFTWARE", "Media"),
        ("El antivirus no detecta amenazas recientes en tiempo real.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía mensajes duplicados a los mismos contactos.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reconoce subtítulos en formato SRT.", "SOFTWARE", "Baja"),
        ("El software de edición de video se cierra al aplicar filtros complejos.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no envía notificaciones a tiempo.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad omite archivos de ciertas carpetas.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad muestra errores al generar reportes fiscales.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene inesperadamente durante la reproducción.", "SOFTWARE", "Media"),
        ("El teclado tiene retraso al escribir rápido varias palabras consecutivas.", "HARDWARE", "Media"),
        ("El ratón inalámbrico se desconecta al cambiar de habitación.", "HARDWARE", "Baja"),
        ("El monitor muestra líneas horizontales al encenderlo.", "HARDWARE", "Alta"),
        ("La batería del portátil pierde carga rápidamente incluso en reposo.", "HARDWARE", "Grave"),
        ("El disco duro interno no arranca y emite pitidos al encender el equipo.", "HARDWARE", "Muy Grave"),
        ("El ventilador del equipo gira a máxima velocidad sin carga.", "HARDWARE", "Media"),
        ("La impresora imprime hojas incompletas o cortadas.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar después de conectar varios dispositivos a la vez.", "HARDWARE", "Baja"),
        ("El portátil no reconoce la tarjeta de sonido interna.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta imágenes con colores incorrectos.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite crear nuevos usuarios correctamente.", "SOFTWARE", "Grave"),
        ("El navegador no recuerda las pestañas abiertas al reiniciar.", "SOFTWARE", "Media"),
        ("El antivirus no actualiza la base de datos de virus recientes.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo filtra incorrectamente mensajes importantes como spam.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce ciertos archivos MP4.", "SOFTWARE", "Baja"),
        ("El software de edición de imágenes no aplica correctamente capas y efectos.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no descarga archivos adjuntos correctamente.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no detecta cambios recientes en carpetas críticas.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera cálculos incorrectos de IVA.", "SOFTWARE", "Alta"),
        ("El reproductor de video pierde sincronización de audio y video al avanzar rápidamente.", "SOFTWARE", "Media"),
        ("El teclado emite caracteres aleatorios al presionar una sola tecla.", "HARDWARE", "Grave"),
        ("El ratón se detiene y se mueve de manera irregular en la pantalla.", "HARDWARE", "Alta"),
        ("El monitor parpadea y se apaga al cambiar la fuente de entrada.", "HARDWARE", "Grave"),
        ("La batería del portátil no carga más del 80% aunque el cargador funcione.", "HARDWARE", "Grave"),
        ("El disco duro externo deja de ser reconocido tras conectar varios archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace ruidos metálicos al arrancar el equipo.", "HARDWARE", "Media"),
        ("La impresora imprime con manchas negras en páginas blancas.", "HARDWARE", "Alta"),
        ("El puerto USB-C no permite transferencia de datos rápida en discos modernos.", "HARDWARE", "Baja"),
        ("El portátil no detecta la memoria RAM instalada correctamente.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra imagen borrosa incluso ajustando el zoom y enfoque.", "HARDWARE", "Alta"),
        ("El sistema operativo se congela al abrir múltiples ventanas simultáneamente.", "SOFTWARE", "Grave"),
        ("El navegador cierra pestañas de manera aleatoria sin advertencia.", "SOFTWARE", "Media"),
        ("El antivirus no detecta malware en archivos recién descargados.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía mensajes duplicados a los mismos contactos.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no carga subtítulos en ciertos videos.", "SOFTWARE", "Baja"),
        ("El software de diseño gráfico se cierra al exportar archivos grandes.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no sincroniza mensajes en tiempo real.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad omite archivos de carpetas específicas.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera duplicados en registros de transacciones.", "SOFTWARE", "Alta"),
        ("El reproductor de video pierde frames y audio al avanzar rápidamente.", "SOFTWARE", "Media"),
        ("El teclado tiene teclas que no responden al presionarlas simultáneamente.", "HARDWARE", "Media"),
        ("El ratón tarda varios segundos en reconectarse tras cambiar de puerto.", "HARDWARE", "Baja"),
        ("El monitor muestra sombras de imágenes anteriores al cambiar de ventana.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga rápidamente al abrir varias aplicaciones.", "HARDWARE", "Grave"),
        ("El disco duro interno genera errores de lectura al copiar archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU no regula la temperatura y el equipo se sobrecalienta.", "HARDWARE", "Grave"),
        ("La impresora imprime documentos con textos borrosos en ciertas páginas.", "HARDWARE", "Alta"),
        ("El puerto USB no detecta dispositivos antiguos correctamente.", "HARDWARE", "Baja"),
        ("El portátil no reconoce la tarjeta gráfica externa conectada.", "HARDWARE", "Muy Grave"),
        ("El proyector pierde calidad de imagen cuando se proyecta en pantalla grande.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite abrir la configuración de red.", "SOFTWARE", "Grave"),
        ("El navegador pierde cookies y sesiones al reiniciar.", "SOFTWARE", "Media"),
        ("El antivirus no bloquea amenazas recientes detectadas en la nube.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía mensajes a destinatarios incorrectos.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia se congela al reproducir archivos en alta resolución.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no guarda los cambios en capas específicas.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no notifica mensajes nuevos correctamente.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad omite carpetas del sistema importantes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera cálculos erróneos en balances financieros.", "SOFTWARE", "Alta"),
        ("El reproductor de video pierde sincronización de audio y video al reproducir videos largos.", "SOFTWARE", "Media"),
        ("El teclado no registra la combinación de teclas Ctrl+Alt+Supr.", "HARDWARE", "Grave"),
        ("El ratón se mueve solo en dirección contraria al deslizarlo.", "HARDWARE", "Alta"),
        ("El monitor pierde la señal al encender el equipo después de dormir.", "HARDWARE", "Grave"),
        ("La batería del portátil se hincha y provoca que la carcasa se deforme.", "HARDWARE", "Muy Grave"),
        ("El disco duro externo no permite copiar archivos mayores a 2GB.", "HARDWARE", "Alta"),
        ("El ventilador del CPU no arranca al encender el equipo.", "HARDWARE", "Muy Grave"),
        ("La impresora imprime con rayas diagonales en todo el documento.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar tras conectar un dispositivo incompatible.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta de red al iniciar el sistema.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra colores distorsionados al proyectar presentaciones.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite instalar controladores nuevos.", "SOFTWARE", "Muy Grave"),
        ("El navegador bloquea descargas de ciertos archivos sin advertencia.", "SOFTWARE", "Alta"),
        ("El antivirus elimina archivos importantes del sistema por error.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo muestra correos duplicados en la bandeja de entrada.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde audio al reproducir videos de larga duración.", "SOFTWARE", "Media"),
        ("El software de edición de video se cierra al aplicar filtros pesados.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no muestra correctamente los mensajes enviados.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar archivos recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad no aplica descuentos correctamente en facturas.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al avanzar a posiciones específicas del archivo.", "SOFTWARE", "Media"),
        ("El teclado no enciende las luces indicadoras al conectarlo.", "HARDWARE", "Baja"),
        ("El ratón inalámbrico pierde señal cuando se aleja más de 2 metros.", "HARDWARE", "Media"),
        ("El monitor muestra colores apagados al cambiar el modo de pantalla.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga incluso estando apagado.", "HARDWARE", "Grave"),
        ("El disco duro interno produce errores al acceder a carpetas grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace un sonido irregular durante el arranque.", "HARDWARE", "Media"),
        ("La impresora imprime páginas con líneas verticales intermitentes.", "HARDWARE", "Alta"),
        ("El puerto USB no reconoce unidades externas nuevas.", "HARDWARE", "Baja"),
        ("El portátil no detecta el adaptador de red Wi-Fi correctamente.", "HARDWARE", "Muy Grave"),
        ("El proyector pierde foco al proyectar imágenes con mucho brillo.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite configurar la fecha y hora correctamente.", "SOFTWARE", "Media"),
        ("El navegador cierra ventanas sin confirmar al navegar por varias pestañas.", "SOFTWARE", "Alta"),
        ("El antivirus no detecta archivos maliciosos descargados recientemente.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo bloquea correos importantes por error.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce archivos con subtítulos incrustados.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no guarda archivos en formato PNG.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no sincroniza mensajes enviados correctamente.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no restaura archivos críticos del sistema.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores al calcular impuestos.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al avanzar más de la mitad del archivo.", "SOFTWARE", "Media"),
        ("El teclado no responde al presionar varias teclas a la vez en juegos.", "HARDWARE", "Alta"),
        ("El ratón muestra movimientos erráticos en superficies oscuras.", "HARDWARE", "Media"),
        ("El monitor tiene brillo irregular en los bordes de la pantalla.", "HARDWARE", "Alta"),
        ("La batería del portátil no mantiene la carga más de una hora.", "HARDWARE", "Grave"),
        ("El disco duro externo genera errores al intentar formatearlo.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU se detiene de manera inesperada causando sobrecalentamiento.", "HARDWARE", "Grave"),
        ("La impresora no detecta cartuchos nuevos automáticamente.", "HARDWARE", "Media"),
        ("El puerto USB deja de funcionar tras conectar varios dispositivos a la vez.", "HARDWARE", "Baja"),
        ("El portátil no reconoce la memoria RAM adicional instalada.", "HARDWARE", "Muy Grave"),
        ("El proyector emite un zumbido constante durante la proyección.", "HARDWARE", "Media"),
        ("El sistema operativo no permite actualizar a la versión más reciente.", "SOFTWARE", "Muy Grave"),
        ("El navegador pierde contraseñas guardadas después de reiniciar.", "SOFTWARE", "Alta"),
        ("El antivirus no detecta virus nuevos al realizar un escaneo completo.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo elimina correos importantes automáticamente.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no carga ciertos formatos de video.", "SOFTWARE", "Media"),
        ("El software de edición de video se cierra al aplicar efectos avanzados.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no descarga archivos adjuntos correctamente.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no detecta cambios recientes en documentos.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula mal los intereses de préstamos.", "SOFTWARE", "Alta"),
        ("El reproductor de video se congela al reproducir archivos en alta resolución.", "SOFTWARE", "Grave"),
        ("El teclado hace doble pulsación al presionar una sola tecla.", "HARDWARE", "Alta"),
        ("El ratón no responde correctamente al usar varias aplicaciones a la vez.", "HARDWARE", "Media"),
        ("El monitor muestra sombras de imágenes previas al cambiar de ventana.", "HARDWARE", "Alta"),
        ("La batería del portátil no retiene carga y provoca apagados inesperados.", "HARDWARE", "Grave"),
        ("El disco duro interno genera sectores defectuosos al guardar archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU gira intermitentemente causando ruidos molestos.", "HARDWARE", "Media"),
        ("La impresora imprime tinta desigual en varias páginas consecutivas.", "HARDWARE", "Alta"),
        ("El puerto USB no reconoce memorias externas nuevas.", "HARDWARE", "Baja"),
        ("El portátil no detecta el adaptador de red al iniciar el sistema.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra colores desalineados al proyectar presentaciones.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite instalar actualizaciones de seguridad.", "SOFTWARE", "Muy Grave"),
        ("El navegador bloquea descargas de ciertos archivos sin notificación.", "SOFTWARE", "Alta"),
        ("El antivirus elimina archivos esenciales del sistema por error.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo duplica correos enviados automáticamente.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce archivos con subtítulos en español.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no aplica filtros correctamente.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no muestra mensajes nuevos correctamente.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no restaura archivos críticos.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula mal descuentos aplicados a facturas.", "SOFTWARE", "Alta"),
        ("El reproductor de video pierde sincronización de audio y video en clips largos.", "SOFTWARE", "Media"),
        ("El teclado no registra teclas repetidas al escribir rápidamente.", "HARDWARE", "Media"),
        ("El ratón se desconecta al cambiar de puerto USB.", "HARDWARE", "Baja"),
        ("El monitor pierde resolución al cambiar la frecuencia de actualización.", "HARDWARE", "Alta"),
        ("La batería del portátil se calienta excesivamente mientras carga.", "HARDWARE", "Grave"),
        ("El disco duro externo se desconecta durante transferencias de archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU emite un sonido constante al iniciar el sistema.", "HARDWARE", "Media"),
        ("La impresora imprime texto borroso al usar tinta nueva.", "HARDWARE", "Alta"),
        ("El puerto USB-C no reconoce dispositivos móviles al conectarlos.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta de memoria SD correctamente.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra la imagen desenfocada incluso ajustando el enfoque.", "HARDWARE", "Grave"),
        ("El sistema operativo se congela al abrir varias aplicaciones pesadas.", "SOFTWARE", "Grave"),
        ("El navegador cierra pestañas sin guardar cambios en formularios.", "SOFTWARE", "Media"),
        ("El antivirus no actualiza las definiciones de virus correctamente.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo muestra correos antiguos como nuevos.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce audio en algunos videos.", "SOFTWARE", "Media"),
        ("El software de edición de video no exporta archivos en alta resolución.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no notifica mensajes nuevos de ciertos contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad omite documentos recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula mal los impuestos en ciertos reportes.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al avanzar a ciertos capítulos de películas largas.", "SOFTWARE", "Media"),
        ("El teclado emite caracteres incorrectos al presionar combinaciones de teclas.", "HARDWARE", "Alta"),
        ("El ratón no responde al presionar los botones laterales.", "HARDWARE", "Media"),
        ("El monitor parpadea al cambiar entre ventanas de alta resolución.", "HARDWARE", "Alta"),
        ("La batería del portátil no carga más allá del 80%.", "HARDWARE", "Grave"),
        ("El disco duro interno hace clics extraños al iniciar el sistema.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU gira demasiado lento causando sobrecalentamiento.", "HARDWARE", "Grave"),
        ("La impresora imprime páginas en blanco intermitentemente.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar al conectar dispositivos con alta potencia.", "HARDWARE", "Baja"),
        ("El portátil no reconoce el disco SSD instalado recientemente.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra líneas horizontales en la pantalla durante presentaciones.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite instalar aplicaciones desde fuentes confiables.", "SOFTWARE", "Muy Grave"),
        ("El navegador bloquea scripts esenciales en algunas páginas web.", "SOFTWARE", "Alta"),
        ("El antivirus no elimina archivos infectados de unidades externas.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no muestra correos enviados correctamente.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia omite fragmentos de audio en ciertos videos.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no aplica cambios en capas seleccionadas.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no sincroniza mensajes en múltiples dispositivos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar archivos recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores al calcular nóminas.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al saltar entre escenas de películas largas.", "SOFTWARE", "Media"),
        ("El teclado no reconoce teclas de función al ejecutar ciertos programas.", "HARDWARE", "Alta"),
        ("El ratón no se desplaza correctamente en pantallas de alta resolución.", "HARDWARE", "Media"),
        ("El monitor tiene una franja negra en el borde derecho al encenderse.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga demasiado rápido durante uso normal.", "HARDWARE", "Grave"),
        ("El disco duro externo genera errores al copiar múltiples archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace ruidos extraños al iniciar programas pesados.", "HARDWARE", "Grave"),
        ("La impresora imprime texto distorsionado en ciertas fuentes.", "HARDWARE", "Alta"),
        ("El puerto USB deja de reconocer teclados externos.", "HARDWARE", "Baja"),
        ("El portátil no detecta tarjetas gráficas externas al conectar docking station.", "HARDWARE", "Muy Grave"),
        ("El proyector muestra imagen torcida al proyectar diapositivas.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite cambiar la configuración de red correctamente.", "SOFTWARE", "Muy Grave"),
        ("El navegador no carga algunas páginas web dinámicas.", "SOFTWARE", "Alta"),
        ("El antivirus no bloquea archivos infectados descargados de internet.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no sincroniza carpetas compartidas.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde subtítulos en ciertos videos.", "SOFTWARE", "Media"),
        ("El software de edición de video no aplica transiciones correctamente.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no actualiza la lista de contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no detecta cambios en documentos recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula mal los balances de cuentas.", "SOFTWARE", "Alta"),
        ("El reproductor de video se congela al saltar a escenas específicas de archivos largos.", "SOFTWARE", "Media"),
        ("El teclado no registra combinaciones de teclas al ejecutar juegos recientes.", "HARDWARE", "Alta"),
        ("El ratón se mueve de manera irregular al usar una alfombrilla nueva.", "HARDWARE", "Media"),
        ("El monitor muestra parpadeos al cambiar la resolución de pantalla.", "HARDWARE", "Alta"),
        ("La batería del portátil no carga completamente y se apaga inesperadamente.", "HARDWARE", "Grave"),
        ("El disco duro interno emite ruidos al copiar archivos pesados.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU gira a máxima velocidad constantemente.", "HARDWARE", "Grave"),
        ("La impresora imprime imágenes con colores incorrectos.", "HARDWARE", "Alta"),
        ("El puerto USB-C no carga dispositivos móviles correctamente.", "HARDWARE", "Baja"),
        ("El portátil no detecta el módulo de memoria RAM adicional.", "HARDWARE", "Muy Grave"),
        ("El proyector pierde nitidez al proyectar presentaciones largas.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite desinstalar programas predeterminados.", "SOFTWARE", "Muy Grave"),
        ("El navegador pierde historial de navegación después de reiniciar.", "SOFTWARE", "Alta"),
        ("El antivirus no actualiza su base de datos correctamente.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía correos duplicados al mismo destinatario.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde audio al reproducir archivos comprimidos.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no guarda cambios en capas ocultas.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no descarga imágenes enviadas por contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar archivos de gran tamaño.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores al calcular descuentos.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al saltar entre capítulos de películas largas.", "SOFTWARE", "Media"),
        ("El teclado presenta teclas pegajosas que dificultan la escritura rápida.", "HARDWARE", "Media"),
        ("El ratón no detecta movimientos precisos en superficies reflectantes.", "HARDWARE", "Baja"),
        ("El monitor muestra tonos de color incorrectos en imágenes claras.", "HARDWARE", "Alta"),
        ("La batería del portátil se calienta demasiado al usar programas pesados.", "HARDWARE", "Grave"),
        ("El disco duro externo se desconecta durante la transferencia de archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace ruido intermitente sin razón aparente.", "HARDWARE", "Media"),
        ("La impresora imprime líneas horizontales en varias páginas consecutivas.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar después de conectar un disco duro externo.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta gráfica adicional al iniciar el sistema.", "HARDWARE", "Muy Grave"),
        ("El proyector pierde enfoque al proyectar videos en alta resolución.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite configurar la red inalámbrica correctamente.", "SOFTWARE", "Muy Grave"),
        ("El navegador cierra pestañas sin guardar cambios en formularios completados.", "SOFTWARE", "Alta"),
        ("El antivirus no elimina archivos sospechosos de unidades externas.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no sincroniza correctamente carpetas compartidas.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde subtítulos al reproducir ciertos videos.", "SOFTWARE", "Media"),
        ("El software de edición de video no aplica transiciones entre clips correctamente.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no notifica mensajes nuevos de ciertos contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no restaura archivos recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula incorrectamente los balances finales.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al reproducir escenas específicas de películas largas.", "SOFTWARE", "Media"),
        ("El teclado no responde a combinaciones de teclas rápidas en juegos recientes.", "HARDWARE", "Alta"),
        ("El ratón se mueve de manera errática al usarlo en superficies oscuras.", "HARDWARE", "Media"),
        ("El monitor tiene zonas con brillo irregular al encender el equipo.", "HARDWARE", "Alta"),
        ("La batería del portátil pierde carga rápidamente al ejecutar aplicaciones pesadas.", "HARDWARE", "Grave"),
        ("El disco duro interno genera ruidos extraños al iniciar el sistema operativo.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU funciona de manera intermitente provocando sobrecalentamiento.", "HARDWARE", "Grave"),
        ("La impresora imprime imágenes borrosas cuando se usan cartuchos nuevos.", "HARDWARE", "Alta"),
        ("El puerto USB deja de reconocer dispositivos móviles al conectarlos.", "HARDWARE", "Baja"),
        ("El portátil no detecta módulos de memoria RAM adicionales al encender.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta la imagen con líneas horizontales al mostrar presentaciones.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite desinstalar aplicaciones preinstaladas.", "SOFTWARE", "Muy Grave"),
        ("El navegador pierde las configuraciones guardadas después de reiniciar.", "SOFTWARE", "Alta"),
        ("El antivirus no actualiza la base de datos de virus correctamente.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía duplicados de correos al mismo destinatario.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia omite audio en algunos videos.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no aplica cambios en capas ocultas.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no descarga archivos enviados por contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar archivos de gran tamaño.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores al calcular descuentos aplicados.", "SOFTWARE", "Alta"),
        ("El reproductor de video se congela al saltar a escenas específicas en películas largas.", "SOFTWARE", "Media"),
        ("El teclado envía caracteres erróneos al presionar varias teclas simultáneamente.", "HARDWARE", "Alta"),
        ("El ratón tiene retraso al moverlo en superficies reflectantes.", "HARDWARE", "Media"),
        ("El monitor presenta sombras al cambiar entre ventanas de aplicaciones.", "HARDWARE", "Alta"),
        ("La batería del portátil no alcanza el 100% de carga completa.", "HARDWARE", "Grave"),
        ("El disco duro externo deja de funcionar durante transferencias grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace ruido constante al ejecutar programas pesados.", "HARDWARE", "Grave"),
        ("La impresora imprime tinta corrida en documentos importantes.", "HARDWARE", "Alta"),
        ("El puerto USB no reconoce dispositivos externos correctamente.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta gráfica al iniciar juegos exigentes.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta la imagen desalineada al mostrar presentaciones.", "HARDWARE", "Grave"),
        ("El sistema operativo bloquea la instalación de actualizaciones críticas.", "SOFTWARE", "Muy Grave"),
        ("El navegador borra historial y marcadores al cerrar.", "SOFTWARE", "Alta"),
        ("El antivirus no detecta amenazas nuevas correctamente.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo muestra mensajes repetidos de la misma conversación.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde audio en ciertos segmentos de videos.", "SOFTWARE", "Media"),
        ("El software de edición de video no guarda transiciones aplicadas.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no recibe notificaciones de nuevos mensajes.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar documentos recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula mal impuestos en ciertos reportes.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al reproducir escenas específicas de películas largas.", "SOFTWARE", "Media"),
        ("El teclado no responde al presionar teclas de función mientras se usan atajos.", "HARDWARE", "Alta"),
        ("El ratón tiene movimientos erráticos al usarlo en superficies con reflejo.", "HARDWARE", "Media"),
        ("El monitor parpadea al cambiar de ventanas o aplicaciones pesadas.", "HARDWARE", "Alta"),
        ("La batería del portátil pierde carga rápidamente al ejecutar programas pesados.", "HARDWARE", "Grave"),
        ("El disco duro interno emite ruidos extraños al iniciar el sistema.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace ruido intermitente y provoca sobrecalentamiento.", "HARDWARE", "Grave"),
        ("La impresora imprime páginas borrosas al usar cartuchos nuevos.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar al conectar dispositivos móviles.", "HARDWARE", "Baja"),
        ("El portátil no detecta memoria RAM adicional instalada correctamente.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta la imagen con líneas horizontales al mostrar presentaciones.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite desinstalar aplicaciones predeterminadas.", "SOFTWARE", "Muy Grave"),
        ("El navegador pierde configuraciones guardadas tras reiniciar el equipo.", "SOFTWARE", "Alta"),
        ("El antivirus no actualiza correctamente la base de datos de virus.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía correos duplicados al mismo destinatario.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia omite audio en algunos videos.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no aplica cambios en capas ocultas.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no descarga archivos enviados por contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar archivos de gran tamaño.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores al calcular descuentos.", "SOFTWARE", "Alta"),
        ("El reproductor de video se congela al saltar a escenas específicas de películas largas.", "SOFTWARE", "Media"),
        ("El teclado no registra caracteres al pulsar varias teclas a la vez.", "HARDWARE", "Alta"),
        ("El ratón pierde precisión al usarlo en superficies oscuras o reflectantes.", "HARDWARE", "Media"),
        ("El monitor muestra parpadeos al abrir aplicaciones con gráficos pesados.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga demasiado rápido incluso en reposo.", "HARDWARE", "Grave"),
        ("El disco duro externo se desconecta durante la transferencia de archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU hace ruido constante provocando sobrecalentamiento.", "HARDWARE", "Grave"),
        ("La impresora imprime páginas con manchas de tinta.", "HARDWARE", "Alta"),
        ("El puerto USB no reconoce dispositivos correctamente al conectar varios al mismo tiempo.", "HARDWARE", "Baja"),
        ("El portátil no detecta tarjetas de memoria adicionales instaladas.", "HARDWARE", "Muy Grave"),
        ("El proyector pierde enfoque al proyectar imágenes en alta resolución.", "HARDWARE", "Grave"),
        ("El sistema operativo bloquea la instalación de actualizaciones críticas.", "SOFTWARE", "Muy Grave"),
        ("El navegador borra historial y marcadores al cerrar.", "SOFTWARE", "Alta"),
        ("El antivirus no detecta amenazas nuevas correctamente.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo muestra mensajes repetidos de la misma conversación.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde audio en ciertos segmentos de video.", "SOFTWARE", "Media"),
        ("El software de edición de video no guarda transiciones aplicadas.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no recibe notificaciones de nuevos mensajes.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar documentos recientes.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula mal impuestos en ciertos reportes.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al reproducir escenas específicas de películas largas.", "SOFTWARE", "Media"),
        ("El teclado deja de registrar teclas tras largos periodos de uso.", "HARDWARE", "Alta"),
        ("El ratón responde lentamente al moverlo en superficies irregulares.", "HARDWARE", "Media"),
        ("El monitor muestra colores apagados al abrir programas de diseño.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga al 50% incluso sin usar aplicaciones.", "HARDWARE", "Grave"),
        ("El disco duro interno hace clics al copiar archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU no funciona al iniciar programas pesados.", "HARDWARE", "Grave"),
        ("La impresora imprime líneas verticales en documentos impresos.", "HARDWARE", "Alta"),
        ("El puerto USB deja de funcionar tras varios usos continuos.", "HARDWARE", "Baja"),
        ("El portátil no reconoce el módulo de memoria RAM nuevo al encender.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta la imagen borrosa al usar resoluciones altas.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite crear nuevas cuentas de usuario.", "SOFTWARE", "Muy Grave"),
        ("El navegador no guarda las contraseñas correctamente.", "SOFTWARE", "Alta"),
        ("El antivirus no detecta malware en archivos comprimidos.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo elimina mensajes importantes automáticamente.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia se detiene al reproducir videos largos.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes pierde cambios al cerrar el programa.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no envía mensajes correctamente a ciertos contactos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no restaura archivos recientes correctamente.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad genera errores al sumar totales de facturas.", "SOFTWARE", "Alta"),
        ("El reproductor de video no reproduce subtítulos correctamente en ciertos archivos.", "SOFTWARE", "Media"),
        ("El teclado emite sonidos extraños al presionar ciertas teclas.", "HARDWARE", "Media"),
        ("El ratón tiene doble clic involuntario al intentar un solo clic.", "HARDWARE", "Alta"),
        ("El monitor pierde señal al cambiar de resolución.", "HARDWARE", "Grave"),
        ("La batería del portátil se hincha levemente después de horas de uso.", "HARDWARE", "Muy Grave"),
        ("El disco duro externo tarda demasiado en ser reconocido por el sistema.", "HARDWARE", "Media"),
        ("El ventilador del CPU se detiene aleatoriamente causando sobrecalentamiento.", "HARDWARE", "Grave"),
        ("La impresora imprime colores distorsionados al usar tinta de repuesto.", "HARDWARE", "Alta"),
        ("El puerto USB deja de reconocer discos flash después de cierto tiempo.", "HARDWARE", "Baja"),
        ("El portátil no detecta la tarjeta gráfica integrada al iniciar juegos.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta imágenes con líneas horizontales en presentaciones largas.", "HARDWARE", "Grave"),
        ("El sistema operativo bloquea la ejecución de programas instalados.", "SOFTWARE", "Muy Grave"),
        ("El navegador cierra pestañas sin advertencia mientras se navega.", "SOFTWARE", "Alta"),
        ("El antivirus genera falsos positivos eliminando archivos esenciales.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo no descarga mensajes de ciertos remitentes.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia pierde sincronización de audio y video.", "SOFTWARE", "Media"),
        ("El software de edición de video no guarda los cambios en proyectos pesados.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no notifica mensajes nuevos de grupos activos.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no restaura archivos de gran tamaño.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad calcula mal impuestos en facturas específicas.", "SOFTWARE", "Alta"),
        ("El reproductor de video se congela al saltar escenas largas.", "SOFTWARE", "Media"),
        ("El teclado no responde al presionar teclas multimedia.", "HARDWARE", "Media"),
        ("El ratón deja de funcionar al cambiar la superficie de uso.", "HARDWARE", "Baja"),
        ("El monitor pierde brillo al usar aplicaciones de gráficos intensivos.", "HARDWARE", "Alta"),
        ("La batería del portátil se descarga más rápido al usar wifi.", "HARDWARE", "Grave"),
        ("El disco duro interno genera errores al copiar archivos grandes.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU vibra de manera irregular al encender el equipo.", "HARDWARE", "Grave"),
        ("La impresora imprime páginas incompletas al usar papel de mayor gramaje.", "HARDWARE", "Alta"),
        ("El puerto USB no detecta dispositivos tras reiniciar el sistema.", "HARDWARE", "Baja"),
        ("El portátil no reconoce unidades externas conectadas a puertos secundarios.", "HARDWARE", "Muy Grave"),
        ("El proyector presenta distorsión de imagen al proyectar colores brillantes.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite acceder a configuraciones del sistema.", "SOFTWARE", "Muy Grave"),
        ("El navegador elimina automáticamente descargas recientes sin permiso.", "SOFTWARE", "Alta"),
        ("El antivirus bloquea aplicaciones esenciales por error.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo envía correos con contenido incompleto.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia no reproduce ciertos formatos de audio.", "SOFTWARE", "Media"),
        ("El software de edición de imágenes no aplica filtros correctamente.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería se cierra inesperadamente al recibir archivos grandes.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad falla al restaurar carpetas completas.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad no genera reportes correctos al aplicar descuentos.", "SOFTWARE", "Alta"),
        ("El reproductor de video se detiene al reproducir clips con subtítulos incrustados.", "SOFTWARE", "Media"),
        ("El teclado emite caracteres repetidos al presionar una sola tecla.", "HARDWARE", "Alta"),
        ("El ratón se mueve solo cuando no se toca, causando errores de puntero.", "HARDWARE", "Muy Grave"),
        ("El monitor pierde nitidez al cambiar entre ventanas con alta resolución.", "HARDWARE", "Alta"),
        ("La batería del portátil no carga más del 80% aunque esté enchufada.", "HARDWARE", "Grave"),
        ("El disco duro externo no se monta en el sistema operativo correctamente.", "HARDWARE", "Muy Grave"),
        ("El ventilador del CPU funciona a máxima velocidad aunque no haya carga.", "HARDWARE", "Grave"),
        ("La impresora imprime páginas con texto borroso en fuentes pequeñas.", "HARDWARE", "Alta"),
        ("El puerto USB se calienta al conectar dispositivos de alto consumo.", "HARDWARE", "Baja"),
        ("El portátil no reconoce discos SSD instalados recientemente.", "HARDWARE", "Muy Grave"),
        ("El proyector proyecta imágenes con colores incorrectos al usar HDMI.", "HARDWARE", "Grave"),
        ("El sistema operativo no permite iniciar sesión con ciertos usuarios.", "SOFTWARE", "Muy Grave"),
        ("El navegador cierra ventanas inesperadamente al abrir múltiples pestañas.", "SOFTWARE", "Alta"),
        ("El antivirus no actualiza la base de datos de virus automáticamente.", "SOFTWARE", "Muy Grave"),
        ("El gestor de correo marca mensajes como leídos sin abrirlos.", "SOFTWARE", "Alta"),
        ("El reproductor multimedia salta partes del video durante la reproducción.", "SOFTWARE", "Media"),
        ("El software de edición de video no aplica correctamente los efectos añadidos.", "SOFTWARE", "Grave"),
        ("La aplicación de mensajería no envía mensajes a ciertos contactos de forma intermitente.", "SOFTWARE", "Media"),
        ("El sistema de copias de seguridad no realiza la sincronización de carpetas correctamente.", "SOFTWARE", "Grave"),
        ("El programa de contabilidad omite transacciones al generar reportes mensuales.", "SOFTWARE", "Alta"),
        ("El reproductor de video no carga subtítulos externos en archivos MKV.", "SOFTWARE", "Media")
    ]

    descripciones = [d[0] for d in datos]
    categorias = [d[1] for d in datos]
    gravedades = [d[2] for d in datos]

    # Crear modelos de texto para cada tipo de salida
    modelo_categoria = make_pipeline(TfidfVectorizer(), MultinomialNB())
    modelo_gravedad = make_pipeline(TfidfVectorizer(), MultinomialNB())

    # Entrenar los modelos
    modelo_categoria.fit(descripciones, categorias)
    modelo_gravedad.fit(descripciones, gravedades)

    # Guardar modelos entrenados
    pickle.dump(modelo_categoria, open("modelo_categoria.pkl", "wb"))
    pickle.dump(modelo_gravedad, open("modelo_gravedad.pkl", "wb"))
#-----------------------------FIN------------------------------#

#-----------------------------Predicir la categoria y gravedad a traves de la descripcion------------------------------#
def predecir(descripcion):
    try:
        modelo_categoria = pickle.load(open("modelo_categoria.pkl", "rb"))
        modelo_gravedad = pickle.load(open("modelo_gravedad.pkl", "rb"))
    except FileNotFoundError:
        return None, None

    categoria = modelo_categoria.predict([descripcion])[0]
    gravedad = modelo_gravedad.predict([descripcion])[0]

    return categoria, gravedad
#-----------------------------FIN------------------------------#

